language: python
python: 2.7
env:
  - TOX_ENV=pypyselects
  - TOX_ENV=pypypoll
  - TOX_ENV=pypyepolls
matrix:
  allow_failures:
    - env: TOX_ENV=pep8
    - env: TOX_ENV=py33selects
    - env: TOX_ENV=py33poll
    - env: TOX_ENV=py33epolls
    - env: TOX_ENV=pypyselects
    - env: TOX_ENV=pypypoll
    - env: TOX_ENV=pypyepolls
install:
  - which pypy
  - sudo add-apt-repository -y ppa:pypy/ppa
  - sudo apt-get update -q
  - sudo apt-get install -q libssl-dev libmysqlclient-dev libpq-dev libzmq3-dev pypy pypy-dev
  - if [[ $TOX_ENV == pypy* ]]; then export PATH=/usr/bin:$PATH; fi;
  - echo $PATH
  - which pypy
  - pip install --upgrade pip setuptools tox virtualenv
before_script:
  - "export EVENTLET_DB_TEST_AUTH='{\"psycopg2\": {\"user\": \"postgres\"}, \"MySQLdb\": {\"passwd\": \"\", \"host\": \"localhost\", \"user\": \"root\"}}'"
script:
  - tox -v -v -e $TOX_ENV
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
